import type { TourDefinition, TourId } from './types';

export const tourSteps: Record<TourId, TourDefinition> = {
  home: {
    id: 'home',
    steps: [
      {
        id: 'home-intro',
        selector: '[data-tour="home-logo"]',
        title: 'Welcome to Tip!',
        body: "Let's take a quick tour of your home feed. Feel free to skip it anytime.",
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 1,
      },
      {
        id: 'home-stats-box',
        selector: '[data-tour="home-stats-box"]',
        title: 'Your Snapshot',
        body: 'Here is a quick view of your profile stats. Click NEXT to see your Recent Visits page.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'home-recent-visits-card',
        selector: '[data-tour="recent-visits-first-card"]',
        title: 'Recent Visits',
        body: 'Each review you make for a dish will be here. Add a personal note for your next visit!',
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 8,
      },
      {
        id: 'home-profile-restaurant',
        selector: '[data-tour="home-featured-profile-restaurant"]',
        title: 'Profiles & Restaurants',
        body: "You can tap a profile or restaurant to open each page. The number on the right shows the review's rating.",
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 4,
      },
      {
        id: 'home-menu-item',
        selector: '[data-tour="home-featured-menu-item-0"]',
        title: 'Menu Items',
        body: 'Rate multiple dishes at once. Click here to explore ratings and photos.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 14,
      },
    ],
  },
  profile: {
    id: 'profile',
    steps: [
      {
        id: 'profile-rank-badge',
        selector: '[data-tour="profile-rank-badge"]',
        title: 'Rank Badge',
        body: 'This is your Rank Badge system. It levels up as you review more places.',
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 8,
      },
      {
        id: 'profile-view-map',
        selector: '[data-tour="profile-view-map"]',
        title: 'Your Map',
        body: 'Open your Food Map anytime to see where you have eaten.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 8,
      },
      {
        id: 'profile-rank-progress',
        selector: '[data-tour="profile-rank-progress"]',
        title: 'Rank Progress',
        body: 'Track your XP and progress toward the next rank here.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 8,
      },
    ],
  },
  create: {
    id: 'create',
    steps: [
      {
        id: 'create-visit-intro',
        selector: '[data-tour="create-visit-intro"]',
        title: 'Start Your Visit',
        body: 'Search for the restaurant you visited and select it to begin your review.',
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'create-add-photo',
        selector: '[data-tour="create-dish-camera"]',
        title: 'Add Photos',
        body: 'Tap the camera to add a dish photo.',
        placement: 'right',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'create-attach-photo',
        selector: '[data-tour="create-media-attach"]',
        title: 'Attach Photos',
        body: 'Assign photos to the right dish.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'create-caption',
        selector: '[data-tour="create-caption-input"]',
        title: 'Caption',
        body: 'Add a quick caption (optional).',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'create-submit',
        selector: '[data-tour="create-submit-button"]',
        title: 'Post It',
        body: "Post your review when you're ready.",
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 10,
      },
    ],
  },
  map_demo: {
    id: 'map_demo',
    steps: [
      {
        id: 'mapdemo-welcome',
        selector: '[data-tour="mapdemo-welcome-anchor"]',
        title: 'My Food Map',
        body: "This is your Food Map - it shows every place you've reviewed and how your journey grows.",
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'mapdemo-pin',
        selector: '[data-tour="mapdemo-pin-card"]',
        title: 'Visit Card',
        body: 'Tap a pin to see a visit card with dishes, notes, and your rating.',
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'mapdemo-empty',
        selector: '[data-tour="mapdemo-empty-stats"]',
        title: 'Your Journey Starts Here',
        body: 'Your map begins at 0 places and 0 countries. Zoom out to see countries as you travel.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 10,
      },
    ],
  },
};
