import type { TourDefinition, TourId } from './types';

export const tourSteps: Record<TourId, TourDefinition> = {
  home: {
    id: 'home',
    steps: [
      {
        id: 'home-intro',
        selector: '[data-tour="home-logo"]',
        title: 'Welcome to Tip!',
        body: 'Quick tour of your home feed. Skip anytime.',
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 2,
      },
      {
        id: 'home-stats-box',
        selector: '[data-tour="home-stats-box"]',
        title: 'Your Snapshot',
        body: 'Quick view of your profile stats. Click next to see all your reviews, and to add your personal notes.',
        placement: 'top',
        blockInteraction: false,
        spotlightPadding: 10,
      },
      {
        id: 'home-recent-visits-page',
        selector: '[data-tour="recent-visits-content"]',
        title: 'Recent Visits',
        body: 'Rate dishes, track restaurants, and add personal notes to remember what you loved.',
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 8,
      },
      {
        id: 'home-profile-photo',
        selector: '[data-tour="home-featured-profile"]',
        title: 'Profiles',
        body: 'Tap a profile to see their reviews.',
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 8,
      },
      {
        id: 'home-restaurant-name',
        selector: '[data-tour="home-featured-restaurant"]',
        title: 'Restaurants',
        body: 'Restaurant names open the full page. The % badge is the quality score.',
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 6,
      },
      {
        id: 'home-menu-item',
        selector: '[data-tour="home-featured-menu-item-0"]',
        title: 'Menu Items',
        body: 'Tap a dish to explore ratings & photos.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 14,
      },
    ],
  },
  profile: {
    id: 'profile',
    steps: [
      {
        id: 'profile-rank-badge',
        selector: '[data-tour="profile-rank-badge"]',
        title: 'Rank Badge',
        body: 'Your badge levels up as you review.',
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 8,
      },
      {
        id: 'profile-view-map',
        selector: '[data-tour="profile-view-map"]',
        title: 'Your Map',
        body: 'See your Food Journey Map anytime.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 8,
      },
      {
        id: 'profile-rank-progress',
        selector: '[data-tour="profile-rank-progress"]',
        title: 'Rank Progress',
        body: 'Earn XP by reviewing more places.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 8,
      },
    ],
  },
  create_step2: {
    id: 'create_step2',
    steps: [
      {
        id: 'create-add-photo',
        selector: '[data-tour="create-dish-camera"]',
        title: 'Add Photos',
        body: 'Tap the camera to add a dish photo.',
        placement: 'right',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'create-attach-photo',
        selector: '[data-tour="create-media-attach"]',
        title: 'Attach Photos',
        body: 'Assign photos to the right dish.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 10,
      },
    ],
  },
  create_step3: {
    id: 'create_step3',
    steps: [
      {
        id: 'create-caption',
        selector: '[data-tour="create-caption-input"]',
        title: 'Caption',
        body: 'Add a quick caption (optional).',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'create-submit',
        selector: '[data-tour="create-submit-button"]',
        title: 'Post It',
        body: 'Post your review when you’re ready.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 10,
      },
    ],
  },
  map_demo: {
    id: 'map_demo',
    steps: [
      {
        id: 'mapdemo-welcome',
        selector: '[data-tour="mapdemo-welcome-anchor"]',
        title: 'Welcome',
        body: 'Every review becomes a pin on your map.',
        placement: 'bottom',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'mapdemo-stats',
        selector: '[data-tour="mapdemo-stats-pill"]',
        title: 'Journey Stats',
        body: 'Track places and countries here.',
        placement: 'top',
        blockInteraction: true,
        spotlightPadding: 10,
      },
      {
        id: 'mapdemo-pin',
        selector: '[data-tour="mapdemo-pin"]',
        title: 'Pins',
        body: 'Tap a pin to preview a restaurant.',
        placement: 'right',
        blockInteraction: true,
        spotlightPadding: 12,
      },
    ],
  },
};
